name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - preprod
    paths:
      - 'frontend/**'
      - '.github/workflows/azure-swa-deploy.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - preprod
    paths:
      - 'frontend/**'

jobs:
  deploy-preprod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/preprod'
    runs-on: ubuntu-latest
    name: Deploy Static Web App (preprod)
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy-preprod
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PREPROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/frontend"
          api_location: ""
          output_location: "build"
        env:
          REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL_PREPROD }}
          REACT_APP_AAD_CLIENT_ID: ${{ vars.REACT_APP_AAD_CLIENT_ID_PREPROD }}
          REACT_APP_AAD_TENANT_ID: ${{ vars.REACT_APP_AAD_TENANT_ID_PREPROD }}
          REACT_APP_AAD_API_SCOPE: ${{ vars.REACT_APP_AAD_API_SCOPE_PREPROD }}
          CI: false

  deploy-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy Static Web App (prod)
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy-prod
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/frontend"
          api_location: ""
          output_location: "build"
        env:
          REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL_PROD }}
          REACT_APP_AAD_CLIENT_ID: ${{ vars.REACT_APP_AAD_CLIENT_ID_PROD }}
          REACT_APP_AAD_TENANT_ID: ${{ vars.REACT_APP_AAD_TENANT_ID_PROD }}
          REACT_APP_AAD_API_SCOPE: ${{ vars.REACT_APP_AAD_API_SCOPE_PROD }}
          CI: false

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PREPROD }}
          action: "close"